version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_production
    ports:
      - "5432:5432"
  api:
    image: node-api-boilerplate-production
    depends_on:
      - db
    ports:
      - "3000:3000"
